# -*- coding: utf-8 -*-
"""Подготовка и предыварительный анализ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a-0d8t-zjQM-kH84Mh_xldyB7xe4L4Gh
"""

from google.colab import files
import pandas as pd

uploaded = files.upload()

data = pd.read_excel('ПР №1. Выборка.xlsx')
data

"""Удаление пустых строк"""

df = data.dropna()
df

"""Создание квартилей для выявления выбросов"""

Q1 = df['Зарплата'].quantile(0.25)
Q3 = df['Зарплата'].quantile(0.75)
Q1, Q3

IQR = Q3 - Q1

min_bound = Q1 - 1.5 * IQR
max_bound = Q3 + 1.5 * IQR
min_bound, max_bound

df_cleaned = df[(df['Зарплата'] >= min_bound)&(df['Зарплата'] <= max_bound)]
df_cleaned

count_orig = data.count()
count_delnul = df.count()
count_clean = df_cleaned.count()
print(f'Исходная таблица:\n {count_orig},\n Таблица после удаления строк с пустыми значениями:\n {count_delnul},\n Таблица после удаления строк с выбросами:\n {count_clean}')

values = df_cleaned.select_dtypes(include='number')
max_values = values.max()
min_values = values.min()
mean_values = values.mean()
print(f'Максимальные значения:\n{max_values}\nМинимальная значения:\n{min_values}\nСредние значения:\n{mean_values}')